# Generated by Django 4.1 on 2022-08-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=30, unique=True, verbose_name='name')),
                ('dean', models.CharField(max_length=30, unique=True, verbose_name='dean')),
                ('office', models.IntegerField(verbose_name='office number')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'College',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='course code')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('des', models.TextField(verbose_name='description')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Current Session',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=5, verbose_name='college')),
                ('degree', models.CharField(choices=[('Asc', 'Associate degree'), ('Bch', "Bachelor's degree"), ('Mas', "Master's degree"), ('Doc', 'Doctoral degree')], max_length=3, verbose_name='degree')),
                ('year', models.IntegerField(verbose_name='year')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Degree',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
                ('dphone', models.CharField(max_length=30, verbose_name='phone')),
                ('office', models.IntegerField(verbose_name='office number')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('agency', models.CharField(max_length=30, verbose_name='agency')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grant',
            },
        ),
        migrations.CreateModel(
            name='OldSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Distinction'), ('B', 'Very good'), ('C', 'Good'), ('D', 'Poor'), ('E', 'Pass'), ('F', 'Fail')], max_length=1, verbose_name='grade')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Old Session',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ssn', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='social security number')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('middleName', models.CharField(max_length=30, verbose_name='middle name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('category', models.CharField(choices=[('Lect', 'Lecturer'), ('Std', 'Student'), ('Grad', 'Graduate')], max_length=4, verbose_name='category')),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1, verbose_name='sex')),
                ('aptNo', models.IntegerField(verbose_name='apartment number')),
                ('laneNo', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30, verbose_name='street')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('zipcode', models.IntegerField(verbose_name='zipcode')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastore.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.DateField(verbose_name='end')),
                ('time', models.IntegerField(verbose_name='time')),
                ('date', models.DateField(auto_now_add=True)),
                ('grant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastore.grant', verbose_name='grant')),
            ],
            options={
                'verbose_name': 'Support',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Cls 1', 'Freshman'), ('Cls 2', 'Sophomore'), ('Cls 3', 'Junior'), ('Cls 4', 'Senior'), ('Cls 5', 'Graduate')], max_length=5, verbose_name='level')),
                ('date', models.DateField(auto_now_add=True)),
                ('Reg', models.ManyToManyField(related_name='students', to='datastore.currentsession', verbose_name='Registered_courses')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_students', to='datastore.department', verbose_name='major')),
                ('minor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_students', to='datastore.department', verbose_name='minor')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='datastore.person', verbose_name='person')),
                ('trspt', models.ManyToManyField(related_name='students', to='datastore.oldsession', verbose_name='transcript')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('qtr', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('3', 'Third Quarter'), ('4', 'Fourth Quarter')], max_length=1, verbose_name='quarter')),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.course', verbose_name='course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.researcher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
        migrations.AddField(
            model_name='researcher',
            name='support',
            field=models.ManyToManyField(to='datastore.support', verbose_name='support'),
        ),
        migrations.AddField(
            model_name='oldsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.session', verbose_name='session'),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('Ast', 'Assistance'), ('Asc', 'Associate'), ('Adj', 'Adjunct'), ('Res', 'Research'), ('Vst', 'Visiting')], max_length=3, verbose_name='rank')),
                ('salary', models.CharField(choices=[('A', 'Below $30,000'), ('B', '$30,000 - $60,000'), ('C', '$61,000 - $90,000'), ('D', '$90,000 - $120,000'), ('E', 'Above $120,000')], max_length=3, verbose_name='salary')),
                ('officeAddress', models.CharField(max_length=50, verbose_name='office address')),
                ('officePhone', models.CharField(max_length=15, verbose_name='office phone')),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='datastore.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Lecturer',
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.lecturer', verbose_name='investigator'),
        ),
        migrations.CreateModel(
            name='Grad_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisee', to='datastore.lecturer', verbose_name='advisor')),
                ('committee', models.ManyToManyField(related_name='thesis_student', to='datastore.lecturer', verbose_name='committee')),
                ('degrees', models.ManyToManyField(to='datastore.degree', verbose_name='degree')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grad', to='datastore.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Graduate',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='HOD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HOD_of', to='datastore.lecturer', verbose_name='Head of department'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='datastore.college', verbose_name='college'),
        ),
        migrations.AddField(
            model_name='department',
            name='lecturers',
            field=models.ManyToManyField(related_name='departments', to='datastore.lecturer', verbose_name='lecturer'),
        ),
        migrations.AddField(
            model_name='currentsession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datastore.session', verbose_name='session'),
        ),
        migrations.AddField(
            model_name='course',
            name='Dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.department', verbose_name='department'),
        ),
    ]
