# Generated by Django 4.1 on 2022-10-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=30, primary_key=True, serialize=False, verbose_name='college')),
                ('dean', models.CharField(max_length=30, unique=True, verbose_name='dean')),
                ('office', models.IntegerField(verbose_name='office number')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'College',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='course code')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('des', models.TextField(verbose_name='description')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('agency', models.CharField(max_length=30, verbose_name='agency')),
                ('start', models.DateField(verbose_name='start date')),
                ('end', models.DateField(verbose_name='end date')),
                ('spend', models.IntegerField(verbose_name='%time spend')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grant',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ssn', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='social security number')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('middleName', models.CharField(max_length=30, verbose_name='middle name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1, verbose_name='sex')),
                ('aptNo', models.IntegerField(verbose_name='apartment number')),
                ('laneNo', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30, verbose_name='street')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('zipcode', models.IntegerField(verbose_name='zipcode')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('ssn', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='social security number')),
                ('firstName', models.CharField(max_length=30, verbose_name='first name')),
                ('middleName', models.CharField(max_length=30, verbose_name='middle name')),
                ('lastName', models.CharField(max_length=30, verbose_name='last name')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('support', models.ManyToManyField(to='datastore.grant', verbose_name='support')),
            ],
            options={
                'verbose_name': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('qtr', models.CharField(choices=[('1', 'First Quarter'), ('2', 'Second Quarter'), ('3', 'Third Quarter'), ('4', 'Fourth Quarter')], max_length=1, verbose_name='quarter')),
                ('grade', models.CharField(blank=True, choices=[('1', 'Excellent'), ('2', 'Good'), ('3', 'Pass'), ('4', 'Fail')], max_length=1, null=True, verbose_name='grade')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.course', verbose_name='course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.researcher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'Section',
            },
        ),
        migrations.CreateModel(
            name='CurrentSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.section')),
            ],
            options={
                'verbose_name': 'Current Section',
            },
            bases=('datastore.section',),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.person')),
                ('rank', models.CharField(choices=[('Ast', 'Assistance'), ('Asc', 'Associate'), ('Adj', 'Adjunct'), ('Res', 'Research'), ('Vst', 'Visiting')], max_length=3, verbose_name='rank')),
                ('salary', models.CharField(choices=[('A', 'Below $30,000'), ('B', '$30,000 - $60,000'), ('C', '$61,000 - $90,000'), ('D', '$90,000 - $120,000'), ('E', 'Above $120,000')], max_length=3, verbose_name='salary')),
                ('officeAddress', models.CharField(max_length=50, verbose_name='office address')),
                ('officePhone', models.CharField(max_length=15, verbose_name='office phone')),
            ],
            options={
                'verbose_name': 'Faculty',
            },
            bases=('datastore.person',),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
                ('dphone', models.CharField(max_length=30, verbose_name='phone')),
                ('office', models.IntegerField(verbose_name='office number')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='datastore.college', verbose_name='college')),
                ('HOD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HOD_of', to='datastore.faculty', verbose_name='Head of department')),
                ('belongs', models.ManyToManyField(related_name='departments', to='datastore.faculty', verbose_name='belongs')),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.department', verbose_name='department'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.person')),
                ('level', models.CharField(choices=[('Cls 1', 'Freshman'), ('Cls 2', 'Sophomore'), ('Cls 3', 'Junior'), ('Cls 4', 'Senior'), ('Cls 5', 'Graduate')], max_length=5, verbose_name='Class')),
                ('Reg', models.ManyToManyField(related_name='registered_students', to='datastore.currentsection', verbose_name='Registered_courses')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_students', to='datastore.department', verbose_name='major')),
                ('minor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_students', to='datastore.department', verbose_name='minor')),
                ('trspt', models.ManyToManyField(related_name='students', to='datastore.section', verbose_name='transcript')),
            ],
            options={
                'verbose_name': 'Student',
            },
            bases=('datastore.person',),
        ),
        migrations.AddField(
            model_name='grant',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.faculty', verbose_name='investigator'),
        ),
        migrations.CreateModel(
            name='Grad_Student',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datastore.student')),
                ('college', models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=5, verbose_name='college')),
                ('degree', models.CharField(choices=[('Asc', 'Associate degree'), ('Bch', "Bachelor's degree"), ('Mas', "Master's degree"), ('Doc', 'Doctoral degree')], max_length=3, verbose_name='degree')),
                ('year', models.IntegerField(verbose_name='year')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisee', to='datastore.faculty', verbose_name='advisor')),
                ('committee', models.ManyToManyField(related_name='thesis_student', to='datastore.faculty', verbose_name='thesis committee')),
            ],
            options={
                'verbose_name': 'Graduate',
            },
            bases=('datastore.student',),
        ),
    ]
