# Generated by Django 4.1.7 on 2024-02-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=30, primary_key=True, serialize=False, verbose_name='name')),
                ('dean', models.CharField(max_length=30, unique=True, verbose_name='dean')),
                ('phone_no', models.CharField(max_length=30, verbose_name='phone')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('middle_name', models.CharField(max_length=30, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('P', 'private')], max_length=1, verbose_name='sex')),
                ('apt_no', models.IntegerField(verbose_name='apartment number')),
                ('lane_no', models.IntegerField(verbose_name='lane number')),
                ('street', models.CharField(max_length=30, verbose_name='street')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('zipcode', models.IntegerField(verbose_name='zipcode')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
                ('phone_no', models.CharField(max_length=30, verbose_name='phone')),
                ('office_no', models.IntegerField(verbose_name='office number')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='dataStore.faculty', verbose_name='faculty')),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataStore.person')),
                ('level', models.CharField(choices=[('Cls 1', 'Freshman'), ('Cls 2', 'Sophomore'), ('Cls 3', 'Junior'), ('Cls 4', 'Senior'), ('Cls 5', 'Graduate')], max_length=5, verbose_name='Class')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_students', to='dataStore.department', verbose_name='major')),
                ('minor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_students', to='dataStore.department', verbose_name='minor')),
            ],
            options={
                'verbose_name': 'Student',
            },
            bases=('dataStore.person',),
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataStore.person')),
                ('rank', models.CharField(choices=[('Ast', 'Assistance'), ('Asc', 'Associate'), ('Adj', 'Adjunct'), ('Res', 'Research'), ('Vst', 'Visiting')], max_length=3, verbose_name='rank')),
                ('salary', models.CharField(choices=[('A', 'Below $30,000'), ('B', '$30,000 - $60,000'), ('C', '$61,000 - $90,000'), ('D', '$90,000 - $120,000'), ('E', 'Above $120,000')], max_length=3, verbose_name='salary')),
                ('office_address', models.CharField(max_length=50, verbose_name='office address')),
                ('office_phone', models.CharField(max_length=15, verbose_name='office phone')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='dataStore.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'Faculty',
            },
            bases=('dataStore.person',),
        ),
    ]
