# Generated by Django 4.1 on 2022-08-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(choices=[('Sci', 'Science'), ('Eng', 'Engineering'), ('Agric', 'Agriculture'), ('Med', 'Medicine'), ('Econ', 'Economic'), ('Gns', 'General studies')], max_length=30, unique=True, verbose_name='college'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datastore.researcher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_students', to='datastore.department', verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='minor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minor_students', to='datastore.department', verbose_name='minor'),
        ),
        migrations.AlterField(
            model_name='support',
            name='time',
            field=models.IntegerField(verbose_name='%time'),
        ),
    ]
