# Generated by Django 4.1 on 2022-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='category',
            field=models.CharField(choices=[('Lect', 'Lecturer'), ('Std', 'Student'), ('Grad', 'Graduate')], max_length=4, verbose_name='category'),
        ),
    ]
